pipeline {
    agent any
    tools {
        "org.jenkinsci.plugins.terraform.TerraformInstallation" "terraform"
    }

    environment {
        TF_HOME = tool('terraform')
        TF_INPUT = "0"
        TF_IN_AUTOMATION = "TRUE"
        TF_LOG = "WARN"
        AWS_ACCESS_KEY_ID = credentials('aws_access_key')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
        PATH = "$TF_HOME:$PATH"
    }

    stages {
        stage('TerraformInit'){
            steps {
                dir('Terraform_Pipeline/'){
                    sh 'terraform --version'
                    sh "terraform init"
                }
            }
        }
        stage('TerraformValidate'){
            steps {
                dir('Terraform_Pipeline/'){
                    sh 'terraform validate'
                }
            }
        }
        stage('TerraformPlan'){
            steps {
                dir('Terraform_Pipeline/'){
                        sh 'terraform plan -out terraform.tfplan'
                }
            }
        }
        stage('TerraformApply'){
            steps {
                script{
                    def apply = false
                    try {
                        input message: 'confirm apply', ok: 'Apply Config'
                        apply = true
                    } catch (err) {
                        apply = false
                        dir('Terraform_Pipeline/'){
                            sh "terraform destroy -auto-approve"
                        }
                        currentBuild.result = 'UNSTABLE'
                    }
                    if(apply){
                        dir('Terraform_Pipeline/'){
                            unstash "terraform-plan"
                            sh 'terraform apply terraform.tfplan'
                        }
                    }
                }
            }
        }
    }
}
